#!/usr/bin/env bash
# Generate gas profiling table for Callora Soroban contracts.
# Runs gas benchmarks across vault, settlement, and revenue_pool,
# parses GAS| lines from test output, and writes a sorted table to BENCHMARKS.md.
#
# Usage:  ./scripts/gas_profile.sh
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$PROJECT_ROOT"

BENCHMARKS_FILE="$PROJECT_ROOT/BENCHMARKS.md"

# Run gas tests and collect GAS| lines.
run_gas_tests() {
  {
    cargo test -p callora-vault --lib -- bench_vault --nocapture 2>/dev/null
    cargo test -p callora-settlement --test gas -- --nocapture 2>/dev/null
    cargo test -p callora-revenue-pool --test gas -- --nocapture 2>/dev/null
  } | grep '^GAS|'
}

# Collect and sort gas profile lines.
sorted_gas=$(run_gas_tests | sort -t'|' -k2)

# Build markdown table.
cat > "$BENCHMARKS_FILE" <<'HEADER'
# Gas Profile

This file is auto-generated by `scripts/gas_profile.sh`. Do not edit by hand.
Last generated: __DATE__

| Entrypoint | CPU Instructions | Memory (bytes) | Description |
|---|---|---|---|
HEADER

while IFS= read -r line; do
  # Parse: GAS| label | cpu | mem | description
  label=$(echo "$line" | cut -d'|' -f2 | xargs)
  cpu=$(echo "$line" | cut -d'|' -f3 | xargs)
  mem=$(echo "$line" | cut -d'|' -f4 | xargs)
  desc=$(echo "$line" | cut -d'|' -f5 | xargs)

  case "$label" in
    vault::init)                         name="Vault"              ep="init"                                 ;;
    vault::deposit)                      name="Vault"              ep="deposit"                              ;;
    vault::deduct)                       name="Vault"              ep="deduct"                               ;;
    vault::batch_deduct_k1)              name="Vault"              ep="batch_deduct(k=1)"                    ;;
    vault::batch_deduct_k10)             name="Vault"              ep="batch_deduct(k=10)"                   ;;
    vault::batch_deduct_k50)             name="Vault"              ep="batch_deduct(k=50)"                   ;;
    vault::withdraw)                     name="Vault"              ep="withdraw"                             ;;
    vault::withdraw_to)                  name="Vault"              ep="withdraw_to"                          ;;
    vault::distribute)                   name="Vault"              ep="distribute"                           ;;
    settlement::init)                    name="Settlement"         ep="init"                                 ;;
    settlement::receive_payment)         name="Settlement"         ep="receive_payment"                      ;;
    settlement::batch_receive_payment_k1)   name="Settlement"      ep="batch_receive_payment(k=1)"           ;;
    settlement::batch_receive_payment_k10)  name="Settlement"      ep="batch_receive_payment(k=10)"          ;;
    settlement::batch_receive_payment_k50)  name="Settlement"      ep="batch_receive_payment(k=50)"          ;;
    settlement::withdraw_developer_balance) name="Settlement"      ep="withdraw_developer_balance"           ;;
    revenue_pool::init)                  name="Revenue Pool"       ep="init"                                 ;;
    revenue_pool::distribute)            name="Revenue Pool"       ep="distribute"                           ;;
    revenue_pool::batch_distribute_k1)   name="Revenue Pool"       ep="batch_distribute(k=1)"                ;;
    revenue_pool::batch_distribute_k10)  name="Revenue Pool"       ep="batch_distribute(k=10)"               ;;
    revenue_pool::batch_distribute_k50)  name="Revenue Pool"       ep="batch_distribute(k=50)"               ;;
    revenue_pool::receive_payment)       name="Revenue Pool"       ep="receive_payment"                      ;;
    *)                                   name="$label"             ep=""                                     ;;
  esac

  printf "| %s | %s | %s | %s | %s |\n" "$name" "$ep" "$cpu" "$mem" "$desc" >> "$BENCHMARKS_FILE"
done <<< "$sorted_gas"

# Replace date placeholder.
sed -i "s/__DATE__/$(date -u '+%Y-%m-%d %H:%M:%S UTC')/" "$BENCHMARKS_FILE"

echo "Wrote $BENCHMARKS_FILE"
